x-default-opts: &default-opts
  restart: unless-stopped
  tty: true
  stdin_open: true
  privileged: false
  ipc: private
  
services:
  node:
    <<: *default-opts
    image: node:22
    container_name: node
    volumes:
      - "./:/app"
    ports:
      - "60080:8080"
    command: sh -c "cd /app && npm install && npm run serve"
